[package]
name = "packager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "4.0.0-beta.2"
wasmer-wasix = "0.7.0"
# wasmer-wasi = "3.1.1"
